# -*- coding: utf-8 -*-
"""Interns.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18CyUq2YfDtgAqgS9Zmw24LJuHc70W7rR
"""

import pandas as pd

list_of_jobs = ['Front-End Engineering Intern', 'Back-End Engineering Intern', 'Full-Stack Software Engineering Intern', 'Information Security Intern',
                'Mobile Engineering Intern', 'Android Engineering Intern', 'Data Scientist Intern', 'Data Engineering Intern']

dataset = pd.read_excel('Scrap_Intern.xlsx')

dataset

dataset.columns

import requests

from bs4 import BeautifulSoup

url = dataset.iloc[: , 1].values
role = dataset.iloc[: , 0].values
status = dataset.iloc[: , -1].values

def is_word_present(my_sentence, my_word = 'intern'): 
  spl_str = my_sentence.split() 
  for temp in spl_str:
    if temp.upper() == my_word.upper():
      return True    
  return False

for i, site in enumerate(url):
  r = requests.get(site)
  print(r.status_code)
  soup = BeautifulSoup(r.content , 'lxml')
  intern_roles = soup.find_all('a')

  for role in intern_roles:
    k = role.text
    if is_word_present(k):
      dataset['Internship Status'][i] = 'Yes'
      break
    else:
      dataset['Internship Status'][i] = 'No'

dataset